# Generated by Django 5.0.7 on 2024-09-24 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_employee_company_remove_employee_department_and_more'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='leave_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leave_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='accounts.profile'),
        ),
    ]
