# Generated by Django 5.0.7 on 2024-10-16 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('management', '0004_alter_company_leave_days_per_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='common.address'),
        ),
    ]
