# Generated by Django 5.0.7 on 2024-10-21 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_company_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='leave_approver',
            new_name='holiday_approver',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='leave_days_per_year',
            new_name='holiday_days_per_year',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='maximum_leave_days_per_request',
            new_name='maximum_holiday_days_per_request',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='minimum_leave_notice',
            new_name='minimum_holiday_notice',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='transferable_leave_days',
            new_name='transferable_holiday_days',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='leave_approver',
            new_name='holiday_approver',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='leave_approver',
            new_name='holiday_approver',
        ),
        migrations.AlterField(
            model_name='team',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='management.company'),
        ),
    ]
