# Generated by Django 5.0.7 on 2024-11-05 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='history',
            name='history_his_content_ebde94_idx',
        ),
        migrations.AddField(
            model_name='history',
            name='object_id',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['content_type', 'object_id'], name='history_his_content_774c23_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['action'], name='history_his_action_75f098_idx'),
        ),
    ]
