# Generated by Django 5.0.7 on 2024-11-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0005_rename_transferable_annual_leave_company_max_carryover_leave",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("company", "name")},
        ),
    ]
