# Generated by Django 5.0.7 on 2024-12-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_remove_team_shift_pattern_shift_team_shift_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="department",
        ),
    ]
