# Generated by Django 5.0.7 on 2024-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_company_max_carryover_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='last_generated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
