# Generated by Django 5.1.4 on 2024-12-18 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="companies.company",
            ),
        ),
    ]
