# Generated by Django 5.1.4 on 2024-12-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_hire",
            field=models.DateField(blank=True, null=True),
        ),
    ]
