# Generated by Django 5.0.7 on 2024-08-25 23:40

import TimeSyncPro.accounts.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_working_on_local_holidays'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='group',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timesyncprouser',
            name='is_company',
        ),
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='normalized_company_name',
            field=models.CharField(default='unknown', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_hire',
            field=models.DateField(blank=True, null=True, validators=[TimeSyncPro.accounts.validators.DateRangeValidator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='days_off_left',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manages_departments',
            field=models.ManyToManyField(blank=True, null=True, related_name='managers', to='management.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrator', 'Administrator'), ('Staff', 'Staff'), ('Team Leader', 'Team Leader'), ('Manager', 'Manager'), ('HR', 'HR')], default='Staff', max_length=13, null=True),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('employee_id', 'company'), name='unique_employee_id_per_company'),
        ),
    ]
