# Generated by Django 5.0.7 on 2024-11-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_is_company_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shift_pattern',
        ),
    ]
