# Generated by Django 5.0.7 on 2024-08-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_timesyncprouser_activation_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('add_administrator', 'Can add Administrator'), ('change_administrator', 'Can change Administrator'), ('delete_administrator', 'Can delete Administrator'), ('view_administrator', 'Can view Administrator'), ('add_hr', 'Can add HR'), ('change_hr', 'Can change HR'), ('delete_hr', 'Can delete HR'), ('view_hr', 'Can view HR'), ('add_manager', 'Can add Manager'), ('change_manager', 'Can change Manager'), ('delete_manager', 'Can delete Manager'), ('view_manager', 'Can view Manager'), ('add_team_leader', 'Can add TeamLeader'), ('change_team_leader', 'Can change TeamLeader'), ('delete_team_leader', 'Can delete TeamLeader'), ('view_team_leader', 'Can view TeamLeader'), ('add_staff', 'Can add Staff'), ('change_staff', 'Can change Staff'), ('delete_staff', 'Can delete Staff'), ('view_staff', 'Can view Staff')]},
        ),
    ]
