# Generated by Django 5.0.7 on 2024-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_employee_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='normalized_company_name',
            new_name='formatted_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
        migrations.AddField(
            model_name='timesyncprouser',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('Staff', 'Staff'), ('Team Leader', 'Team Leader'), ('Manager', 'Manager'), ('HR', 'HR'), ('Administrator', 'Administrator')], default='Staff', max_length=13, null=True),
        ),
    ]
