# Generated by Django 5.0.7 on 2024-09-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_company_email_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesyncprouser',
            name='activation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
