# Generated by Django 5.0.7 on 2024-09-24 08:32

import TimeSyncPro.accounts.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_timesyncprouser_activation_token'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manages_departments',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift_pattern',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='company',
            name='formatted_name',
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('employee_id', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('role', models.CharField(blank=True, choices=[('Staff', 'Staff'), ('Team Leader', 'Team Leader'), ('Manager', 'Manager'), ('HR', 'HR'), ('Administrator', 'Administrator')], default='Staff', max_length=13, null=True)),
                ('date_of_hire', models.DateField(blank=True, null=True, validators=[TimeSyncPro.accounts.validators.validate_date_of_hire])),
                ('days_off_left', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[TimeSyncPro.accounts.validators.phone_number_validator])),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='accounts.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='management.department')),
                ('manages_departments', models.ManyToManyField(related_name='managers', to='management.department')),
                ('shift_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='management.shiftpattern')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='management.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('add_administrator', 'Can add Administrator'), ('change_administrator', 'Can change Administrator'), ('delete_administrator', 'Can delete Administrator'), ('view_administrator', 'Can view Administrator'), ('add_hr', 'Can add HR'), ('change_hr', 'Can change HR'), ('delete_hr', 'Can delete HR'), ('view_hr', 'Can view HR'), ('add_manager', 'Can add Manager'), ('change_manager', 'Can change Manager'), ('delete_manager', 'Can delete Manager'), ('view_manager', 'Can view Manager'), ('add_team_leader', 'Can add TeamLeader'), ('change_team_leader', 'Can change TeamLeader'), ('delete_team_leader', 'Can delete TeamLeader'), ('view_team_leader', 'Can view TeamLeader'), ('add_staff', 'Can add Staff'), ('change_staff', 'Can change Staff'), ('delete_staff', 'Can delete Staff'), ('view_staff', 'Can view Staff')],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='leave_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='accounts.profile'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('employee_id', 'company'), name='unique_employee_id_per_company'),
        ),
    ]
