# Generated by Django 5.0.7 on 2024-10-05 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_company_leave_approver'),
        ('management', '0003_company_alter_department_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='management.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
