# Generated by Django 5.0.7 on 2024-12-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='days_requested',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
