# Generated by Django 5.0.7 on 2024-12-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0003_holiday_days_requested"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="holiday",
            options={
                "ordering": ["start_date"],
                "permissions": [
                    ("can_view_all_holidays", "Can view all holiday requests"),
                    ("can_update_holiday_status", "Can update holiday status"),
                ],
            },
        ),
    ]
