# Generated by Django 5.0.7 on 2024-12-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0007_absence_days_of_absence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="absence",
            options={
                "ordering": ["start_date"],
                "permissions": [
                    ("view_all_absences", "Can view all absences"),
                    ("view_department_absences", "Can view department absences"),
                    ("view_team_absences", "Can view own absences"),
                    ("view_absences", "Can view absences"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="holiday",
            options={
                "ordering": ["start_date"],
                "permissions": [
                    ("view_all_holidays_requests", "Can view all holiday requests"),
                    (
                        "view_department_holidays_requests",
                        "Can view department holiday requests",
                    ),
                    ("view_team_holidays_requests", "Can view own holiday requests"),
                    ("update_holiday_requests_status", "Can update holiday status"),
                    ("view_holidays_requests", "Can view holiday requests"),
                ],
            },
        ),
    ]
